### ISSUE TITLE
Werk mobile-first!

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/fix-the-flow-interactive-website#11]
Werk mobile-first aan de hand van een min-width media query!

https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/style.css#L173

**Comment by OFRqq** [comment]
is inderdaad handiger, zie [hier](https://github.com/OFRqq/look-and-feel-corporate-identity/blob/85500ba15a8c4214c52090860e380b5206f5f300/partners.css#L18C1-L222C2)
