### ISSUE TITLE
Denk aan je tabs en inline-styling 

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/fix-the-flow-interactive-website#13]
Let erop dat je tabs goed gebruikt, je nav staat voor je header terwijl die erin zit, dit is slecht leesbaar. Net een image in een anchor, doe dit op een nieuwe regel.

En gebruik geen inline-styling! 

https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L12-L28

**Comment by OFRqq** [comment]
Deze [repo ](https://github.com/OFRqq/The-client-website-2)word op dit moment niet meer gebruikt, bij de nieuwe [repo ](https://github.com/OFRqq/fix-the-flow-interactive-website)heb ik gelet op inline-styling en [toegepast](https://github.com/OFRqq/fix-the-flow-interactive-website/blob/9a50e406941a1136eda5df057d63a441b250f759/Partners.html#L14C5-L26C11). 

[img + anchor ](https://github.com/OFRqq/fix-the-flow-interactive-website/commit/9ff520c83fa55f03c00027a2e08a5704d9a12948)

**Comment by rutgerkock** [comment]
Je tabs zien er beter uit, maar je gebruikt nog steeds inline-styling --> height: 50px;

Doe dit in een CSS bestand, dit is onhandig.
