### ISSUE TITLE
Denk dat hier een afbeelding mist? + indentin

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/fix-the-flow-interactive-website#14]
Denk dat een afbeelding mist? Zo nee, fix je lettertype, is amper leesbaar. Denk ook aan je tabs, je code is slecht leesbaar.
https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L30-L38

**Comment by OFRqq** [comment]
[de oude website](https://github.com/OFRqq/The-client-website-2) is buiten gebruik, bij [de nieuwe website](https://github.com/OFRqq/look-and-feel-corporate-identity) zal ik op leesbaarheid letten bij het gebruik van bijv src
