### ISSUE TITLE
Feedback Colin en Yamen

### ISSUE THREAD

**Issue by ColindeGroot** [OFRqq/fix-the-flow-interactive-website#15]
de gedeelde stylesheet conflicteert met je huidige stylesheet. De kleurgebruik en algemene indeling van de geelde stylesheet (styleguide) ziet er wel netjes uit. Classnames (client website 2) zijn vrij consistent maar indeling zou iets netter kunnen 

- zorg ervoor dat alle algemene styling enkel uit de styleguide komt zodat het niet conflicteert.

**Comment by OFRqq** [comment]
in mijn [active repo](https://github.com/OFRqq/look-and-feel-corporate-identity) gebruik ik 2 stylesheets waarbij de [styleguide-sheet ](https://kimnikitaschijf.github.io/look-and-feel-styleguide/biebinbloei.css)boven de partner.css-sheet staat (zie [hier](https://github.com/OFRqq/look-and-feel-corporate-identity/blob/85500ba15a8c4214c52090860e380b5206f5f300/Partners.html#L5C3-L6C46)), hierdoor zal die voorrang hebben bij het gebruik ervan en conflict deze niet meer met partner.css 
(ook omdat dingen niet meer dubbelop staan in de partner.css en in de stylesheet)

_algemene styling komt nu enkel uit styleguide_
