### ISSUE TITLE
w3c validator

### ISSUE THREAD

**Issue by yujing-student** [OFRqq/fix-the-flow-interactive-website#17]
de <a> kan je beter buiten de button zetten of maak met css de <a> een button qua vormgeving want dit is niet semantisch

![image](https://github.com/user-attachments/assets/af63b780-6fd6-40c8-a47a-25983cfa5ff7)

zier hier de documentatie:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by OFRqq** [comment]
oude website is eruit gehaald, probleem word niet herhaald, zie [hier](https://github.com/OFRqq/fix-the-flow-interactive-website/commit/9ff520c83fa55f03c00027a2e08a5704d9a12948).
