### ISSUE TITLE
code/design review

### ISSUE THREAD

**Issue by julesbruins** [OFRqq/fix-the-flow-interactive-website#20]
**_code review_**
1) De comments staan beschreven. 
2) De variabelen zijn prima. 
3) Er wordt geen styling toegevoegd in de JS.

**_design review_**
1) Feedforward: Je ziet 'next' staan. En je hebt drie bolletjes waarvan de geselecteerde zwart is. Er zit een :hover.
2) Feedback: Die bolletjes veranderen, de volgende card komt.
3) Misschien ook handig om terug te gaan naar de vorige card. Misschien de link wat duidelijker maken op de card. Op de bolletjes klikken zou ook handig zijn.

**Comment by Karima002** [comment]
Feedback gegeven door @Saif8599 @karima002 @julesbruins
