### ISSUE TITLE
Zou je dit niet doen met een toggle classlist?

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/fix-the-flow-interactive-website#4]
zie: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
Nettere oplossing denk ik

https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L74-L86

**Comment by OFRqq** [comment]
de specifieke js werkt niet atm, ik zal hier morgen naar kijken en anders eventueel weglaten
