### ISSUE TITLE
Zou JS in een apart bestand zetten

### ISSUE THREAD

**Issue by rutgerkock** [OFRqq/fix-the-flow-interactive-website#8]
https://github.com/OFRqq/The-client-website-2/blob/132246dfeb816907656ba52b8ea92b13e185d90f/index.html#L63

Zou JS in een apart bestand zetten, overzichtelijker

**Comment by OFRqq** [comment]
https://github.com/OFRqq/look-and-feel-corporate-identity/blob/main/scripts.js
